.name "zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk "
.comment "zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk zorkkkkkk \0\0\0\0"

live:	live %1

l2:		lld 4096, r2
		sti r2, %:live, %1
		sti r2, %:live, %1

live:	live %1
